// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/frabits/frabit/pkg/api"
	"github.com/frabits/frabit/pkg/bus"
	"github.com/frabits/frabit/pkg/config"
	"github.com/frabits/frabit/pkg/infra/db"
	"github.com/frabits/frabit/pkg/infra/remotecache"
	"github.com/frabits/frabit/pkg/server/bg_services"
	"github.com/frabits/frabit/pkg/services/access_control"
	"github.com/frabits/frabit/pkg/services/agent"
	"github.com/frabits/frabit/pkg/services/apikey"
	"github.com/frabits/frabit/pkg/services/audit"
	"github.com/frabits/frabit/pkg/services/authn"
	"github.com/frabits/frabit/pkg/services/backup"
	"github.com/frabits/frabit/pkg/services/cleanup"
	"github.com/frabits/frabit/pkg/services/deploy"
	"github.com/frabits/frabit/pkg/services/license"
	"github.com/frabits/frabit/pkg/services/login"
	"github.com/frabits/frabit/pkg/services/notifications"
	"github.com/frabits/frabit/pkg/services/org"
	"github.com/frabits/frabit/pkg/services/role"
	"github.com/frabits/frabit/pkg/services/secrets"
	"github.com/frabits/frabit/pkg/services/serviceaccount"
	"github.com/frabits/frabit/pkg/services/session"
	"github.com/frabits/frabit/pkg/services/settings"
	"github.com/frabits/frabit/pkg/services/team"
	"github.com/frabits/frabit/pkg/services/updatechecker"
	"github.com/frabits/frabit/pkg/services/user"
	"github.com/google/wire"
)

// Injectors from wire.go:

func Initialize() (*Server, error) {
	configConfig := config.ProviderConfig()
	metaStore, err := db.New(configConfig)
	if err != nil {
		return nil, err
	}
	service := secrets.ProviderSecrets(configConfig)
	userService := user.ProviderService(configConfig, metaStore, service)
	roleService := role.ProviderService()
	access_controlService := access_control.ProviderService(metaStore)
	accessControl := access_control.ProviderAccessControl(userService, roleService, access_controlService)
	sessionService := session.ProviderService(configConfig, metaStore)
	loginService := login.ProviderLoginNative(configConfig, metaStore)
	apikeyService := apikey.ProviderService(configConfig, metaStore, userService)
	authnService := authn.ProviderService(configConfig, loginService, apikeyService, userService, service)
	backupService := backup.ProviderMySQLBackup()
	deployService := deploy.ProviderService()
	agentService := agent.ProviderAgentService(configConfig, metaStore)
	orgService := org.ProviderService(configConfig, metaStore)
	teamService := team.ProviderService(configConfig, metaStore)
	notificationsService := notifications.ProviderService()
	verifier := user.ProviderVerifier(configConfig, notificationsService, userService, service)
	busBus := bus.ProviderBus()
	auditService := audit.ProviderService(configConfig, metaStore, busBus)
	serviceaccountService := serviceaccount.ProviderService(apikeyService, userService, orgService)
	settingsService := settings.ProviderService(service, metaStore)
	licenseService := license.ProviderService(configConfig, metaStore)
	remoteCache := remotecache.ProviderRemoteCache(configConfig, metaStore, service)
	httpServer := api.ProviderHTTPServer(configConfig, accessControl, sessionService, authnService, backupService, deployService, agentService, loginService, orgService, teamService, userService, verifier, auditService, busBus, serviceaccountService, apikeyService, settingsService, service, licenseService, remoteCache)
	cleanupService := cleanup.ProviderService()
	frabitService := updatechecker.ProviderFrabitService()
	backgroundServiceRegistry := bg_services.ProviderBackgroundServiceRegistry(cleanupService, notificationsService, deployService, frabitService, licenseService, remoteCache, authnService)
	server := NewServer(configConfig, httpServer, backgroundServiceRegistry, metaStore)
	return server, nil
}

// wire.go:

var wireSet = wire.NewSet(db.New, access_control.ProviderAccessControl, access_control.ProviderService, authn.ProviderService, apikey.ProviderService, config.ProviderConfig, agent.ProviderAgentService, session.ProviderService, audit.ProviderService, backup.ProviderMySQLBackup, bus.ProviderBus, cleanup.ProviderService, deploy.ProviderService, login.ProviderLoginNative, license.ProviderService, serviceaccount.ProviderService, secrets.ProviderSecrets, settings.ProviderService, role.ProviderService, remotecache.ProviderRemoteCache, notifications.ProviderService, org.ProviderService, team.ProviderService, user.ProviderService, user.ProviderVerifier, updatechecker.ProviderFrabitService, bg_services.ProviderBackgroundServiceRegistry, api.ProviderHTTPServer, NewServer)
